name: Create Desktop Snapshot

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Install virtual framebuffer (if not available) to allow running GUI on a headless server
        run: command -v Xvfb >/dev/null 2>&1 || { sudo apt update && sudo apt install -y xvfb; }

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Build/Install Snapshot
        run: |
          export DISPLAY=":1"
          Xvfb :1 -screen 0 800x600x8 &
          mvn -U -B clean -P windows-linux install -T 1C
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Rename before upload
        run: |
          mkdir izpack
          # move jar from work dir to izpack dir
          mv /home/runner/work/forge/forge/forge-installer/*/*.jar izpack/
          
          cd izpack
          d=$(date +%m.%d)
          # rename files and append date
          for file in *.jar; do
            bname="${file%.*}"
            echo "file renamed to ${bname}-${d}.jar"
            mv "${bname}.jar" "${bname}-${d}.jar"
          done

      - name: 📦 Upload .jar as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-snapshot-${{ github.run_id }}
          path: izpack/*.jar

      - name: Send failure notification to Discord
        if: failure() # This step runs only if the job fails
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"🔴 Desktop Snapshot Build Failed in branch: \`${{ github.ref_name }}\` by \`${{ github.actor }}\`.\nCheck logs: ${{ github.run_url }}\"}" \
          ${{ secrets.DISCORD_AUTOMATION_WEBHOOK }}
